# Welcome to Serverless!
app: todo-service
org: phuthuyxam
service: todo-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  stage: dev
  region: ap-southeast-1

functions:
  todoListCreate:
    handler: src/handlers.createTodoList
    events:
        - httpApi:
            path: /todo-list
            method: post
  allTodoList:
    handler: src/handlers.allTodoList
    events:
        - httpApi:
            path: /todo-list
            method: get
  getTodo:
    handler: src/handlers.getTodo
    events:
        - httpApi:
            path: /todo-list/{id}
            method: get
  updateTodoList:
    handler: src/handlers.updateTodoList
    events:
        - httpApi:
            path: /todo-list/{id}
            method: put
  deleteTodoItem:
    handler: src/handlers.deleteTodoItem
    events:
      - httpApi:
          path: /todo-list/{id}
          method: delete

plugins:
  - serverless-plugin-typescript
  - serverless-offline
